# Generated by Django 5.1.4 on 2025-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_options_remove_product_amazon_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_amazon_product',
            field=models.BooleanField(default=False),
        ),
    ]
