# Generated by Django 5.1.4 on 2025-01-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_is_amazon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='static_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
